#spring.datasource.url=jdbc:postgresql://localhost:5432/Pilotos
#spring.datasource.username=postgres
#spring.datasource.password=DUpar$3156
#spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto=update

#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/Pilotos
#    username: postgres
#    password: DUpar$3156
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    hibernate:
#      ddl-auto: update

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: 2fru94qi7M7fVF5FrAKsUeERjuzlUip5
            client-secret: 7_iWK0hBkF5_ePgA6iH8j0RDKufHgAODIVQzdEWldvkSgIy_nxKF4QrXtTe_BC33
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://dev-hw16l2kz.us.auth0.com/